### ISSUE TITLE
Configuration of paths

### ISSUE THREAD

**Issue by sweetroll** [mister-bk/craft-plugin-mix#1]
Thanks for making this plugin!

Is the settings link missing from the plugin page? I found the page at 'admin/settings/plugins/mix' but would be good to get a link too.

**Comment by jackmu95** [comment]
There is a settings link in the plugin page:

![craft_plugin_mix_settings_link](https://cloud.githubusercontent.com/assets/2737132/26224965/37592bae-3c25-11e7-9b15-8d12327d4f9a.png)

**Comment by sweetroll** [comment]
Not seeing it. Test on beta.7 and beta.17.
<img width="1192" alt="screen shot 2017-05-19 at 8 51 55 am" src="https://cloud.githubusercontent.com/assets/462429/26236672/d769c472-3c71-11e7-92ee-53acd4eb2fe7.png">

**Comment by jackmu95** [comment]
This is weird. Do you have any other plugins installed where the settings link is present?

**Comment by sweetroll** [comment]
@jackmu95 just added another and doesnt have settings icon... must be a dodgy craft install.

Apologies!
