### ISSUE TITLE
Not picking up versioned assets

### ISSUE THREAD

**Issue by terryupton** [mister-bk/craft-plugin-mix#11]
Hi, think I must be missing something or not have the settings correct, but I cannot figure out what is amis?

In a Twig template I have:
`<link rel="stylesheet" href="{{ mix('css/style.css') }}">`

Which outputs the following into the browser:
`<link rel="stylesheet" href="/assets/css/style.css">`

That's not loading in the versioned asset.
My mix-manifest.json looks like this:
```
{
    "/web/assets/js/index.js": "/web/assets/js/index.js?id=5e702572675a6cab4dfa",
    "/web/assets/css/style.css": "/web/assets/css/style.css?id=1f39aea0608bf0bfd36c",
    "/web/assets/js/index.es5.js": "/web/assets/js/index.es5.js?id=51f580901c35d8bfaed2"
}
```
Shouldn't the browser output look like this instead?
`<link rel="stylesheet" href="/assets/css/style.css?id=1f39aea0608bf0bfd36c">` or even better if I can get it to output `<link rel="stylesheet" href="/assets/css/style.1f39aea0608bf0bfd36c.css">`

Here is my mix setup:
`.setPublicPath(path.resolve('./'))`

in the plugin settings I have set the Public Path to `web` and the Assets path to `Assets`

Any ideas what i've missed?

Thanks.

**Comment by jackmu95** [comment]
@terryupton The public path for `laravel-mix` isn't correctly configured.
Make sure to set it to `web/` by using `mix.setPublicPath('web/')` in `webpack.mix.js`.
