### ISSUE TITLE
"Lazily" find a versioned file?

### ISSUE THREAD

**Issue by vaughn-taylor** [mister-bk/craft-plugin-mix#12]
Hi, is it possible that you can describe the differences in the usage methods with a little more detail? For example, when would I use this method:

    <script src="{{ mix('js/main.js') }}"></script>

Over this method:

    {{ craft.mix.withTag('js/main.js') | raw }}

**Comment by dominikfeilbach** [comment]
Please excuse the late feedback.
**The above example does not differ in output.**

``` {{ craft.mix.withTag('js/main.js') | raw }} ``` internally calls the above function and just adds the script-tag with src or the style-tag with href based on the file extension
