### ISSUE TITLE
Customize the mix config file

### ISSUE THREAD

**Issue by shaqaruden** [mister-bk/craft-plugin-mix#14]
With normal mix you edit webpack.mix.js. I don't see this file anywhere.

Shouldn't I need to run npm run dev to compile my js? I also want to add the tailwind larval mix plugin.

or do I still need to do the standard Laravel Mix install?

**Comment by jackmu95** [comment]
@shaqaruden The installation and usage of Mix is completely up to you.

This plugin only provides an easy way to include the files generated by Mix in your Craft template files.
