### ISSUE TITLE
Craft 4 compatibility?

### ISSUE THREAD

**Issue by angieherrera** [mister-bk/craft-plugin-mix#21]
Will this work with Craft 4?

**Comment by Alexanderoff** [comment]
+1

**Comment by robzor** [comment]
Does anyone know what is causing it to not be compatible?

**Comment by robzor** [comment]
https://github.com/mister-bk/craft-plugin-mix/pull/20

Ooh there is a fork here

**Comment by darylknight** [comment]
Subscribing. We use this on literally all of our websites, so I'd love to see this updated soon
![image](https://user-images.githubusercontent.com/1250017/166912388-1625ad59-1f35-4029-9bc3-f31f397c3ad6.png)

**Comment by amici-infotech** [comment]
I would love to see this upgraded in Craft v4

**Comment by robzor** [comment]
this has a Craft 4 version and I believe does the same thing? 

https://github.com/leowebguy/mix-manifest

**Comment by taher-amici** [comment]
> this has a Craft 4 version and I believe does the same thing?
> 
> https://github.com/leowebguy/mix-manifest

I don't think this plugin is same as mix. i suggest use this fork until merge.

**Comment by eyekiller-hub** [comment]
Yes would love a Craft 4 version

**Comment by engram-design** [comment]
Just to chime in, we've added this to our [Craft 3 migration project](https://verbb.io/craft-3). If it gets enough votes, we'll migrate this plugin to Craft 4 and continue to work on it, giving it a new home, and keeping it open source.

Do let us know if you plan to make the plugin Craft 4 compatible! @jacobmllr95

**Comment by darylknight** [comment]
Without wanting to tread on anyone's toes, another solution is to use [Twigpack](https://plugins.craftcms.com/twigpack) which has already been updated for Craft 4. We've been moving all our sites to that so we can update them. In your _layout.twig file, replace the previous reference to Mix's CSS and JavaScript with this:

```
{# Stylesheet #}
{{ craft.twigpack.includeCssModule('/css/app.css') }}

{# Javascript #}
{{ craft.twigpack.includeJsModule('/js/app.js') }}
```

Below is the twigpack config file we're using as a drop-in solution for how we had the Mix plugin setup:

```
<?php
/**
 * Twigpack plugin for Craft CMS 3.x
 *
 * Twigpack is the conduit between Twig and webpack, with manifest.json &
 * webpack-dev-server HMR support
 *
 * @link      https://nystudio107.com/
 * @copyright Copyright (c) 2018 nystudio107
 */

/**
 * Twigpack config.php
 *
 * This file exists only as a template for the Twigpack settings.
 * It does nothing on its own.
 *
 * Don't edit this file, instead copy it to 'craft/config' as 'twigpack.php'
 * and make your changes there to override default settings.
 *
 * Once copied to 'craft/config', this file will be multi-environment aware as
 * well, so you can have different settings groups for each environment, just as
 * you do for 'general.php'
 */

return [
	// Global settings
	'*' => [
		// If `devMode` is on, use webpack-dev-server to all for HMR (hot module reloading)
		'useDevServer' => false,
		// Enforce Absolute URLs on includes
		'useAbsoluteUrl' => true,
		// The JavaScript entry from the manifest.json to inject on Twig error pages
		// This can be a string or an array of strings
		'errorEntry' => '',
		// String to be appended to the cache key
		'cacheKeySuffix' => '',
		// Manifest file names
		'manifest' => [
			'legacy' => 'mix-manifest.json',
			'modern' => 'mix-manifest.json',
		],
		// Public server config
		'server' => [
			'manifestPath' => '@webroot/assets/',
			'publicPath' => '/assets/',
		],
		// webpack-dev-server config
		'devServer' => [
			'manifestPath' => '@webroot/assets/',
			'publicPath' => '/assets/',
		],
		// Bundle to use with the webpack-dev-server
		'devServerBuildType' => 'modern',
		// Whether to include a Content Security Policy "nonce" for inline
		// CSS or JavaScript. Valid values are 'header' or 'tag' for how the CSP
		// should be included. c.f.:
		// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_inline_script
		'cspNonce' => '',
		// Local files config
		'localFiles' => [
			'basePath' => '@webroot/',
			'criticalPrefix' => '/dist/criticalcss/',
			'criticalSuffix' => '_critical.min.css',
		],
	],
	// Live (production) environment
	'live' => [],
	// Staging (pre-production) environment
	'staging' => [],
	// Development environment
	'dev' => [
		// If `devMode` is on, use webpack-dev-server to all for HMR (hot module reloading)
		// 'useDevServer' => true,
	],
];

```

**Comment by sunscreem** [comment]
Another options, as mentioned above by @robzor - I've been using this. Now in production on 10+ craft 4 sites and works well - https://github.com/leowebguy/mix-manifest

**Comment by engram-design** [comment]
Can confirm Twigpack is something we used to use @darylknight (before moving to Vite), and I'll admit I've never used this plugin before with Laravel Mix!

So sounds like there might be a few options out there already that are sufficient?

**Comment by taher-amici** [comment]
There are few thing you can't do with Vite and  I am using this plugin in my all sites.

**Comment by mofman** [comment]
As others have said https://github.com/leowebguy/mix-manifest does not offer the ability to change config per environment eg public path or asset path. 

According to https://plugins.craftcms.com/mix?cmsConstraint=%5E4.0 there are  8,850 active installs of this plugin so it's defintiely a huge blocker for people to wanting to upgrade.

**Comment by engram-design** [comment]
I would _still_ recommend using [Twigpack](https://plugins.craftcms.com/twigpack) which we used for years with Laravel Mix without issue. What benefits does this plugin provide over Twigpack? Laravel Mix being a layer over Webpack should be pretty compatible to my knowledge and own experience.

I'm happy to take over this plugin if the author is no longer maintaining it, but just want to be sure I'm not missing something that you can already achieve with Twigpack?

**Comment by robzor** [comment]
> I would _still_ recommend using [Twigpack](https://plugins.craftcms.com/twigpack) which we used for years with Laravel Mix without issue. What benefits does this plugin provide over Twigpack? Laravel Mix being a layer over Webpack should be pretty compatible to my knowledge and own experience.
> 
> I'm happy to take over this plugin if the author is no longer maintaining it, but just want to be sure I'm not missing something that you can already achieve with Twigpack?

Honestly, I think simplicity is the reason. Also, the name of the plugin meaning it came up in the search results for Plugins to work with Mix. Twigpack looks great and personally, I might start using it, but this plugin is the first thing a developer will find when looking for something to integrate with Mix.

**Comment by thisisjamessmith** [comment]
I don't know about anyone else, and maybe it's changed since I last tried a few years ago, but I spent _days_ getting Twigpack to work the way I wanted it to, and although I eventually succeeded, I ended up with an opaque and complicated setup that I didn't fully understand. It's too complex for simple websites and I was super relieved to fall back to the simplicity of Mix, and this probably goes double for any junior devs on the team. (To be fair, I still don't fully understand the interaction between Mix and Webpack, but at least I don't really need to).

**Comment by engram-design** [comment]
@robzor Valid point! I'm purely thinking of maintainability (if another tool out there can do it, why have another one, etc)

@thisisjamessmith I want to stress that you can use Laravel Mix and Twigpack, while keeping things pretty simple. You don't need to mess around with Webpack. Although it depends what you mean by "the way I wanted to" - we're all different!

To illustrate, we used the following in `/config/twigpack.php`

```php
<?php

return [
    // Global settings
    '*' => [
        'useDevServer' => true,
        'manifest' => [
            'legacy' => 'mix-manifest.json',
            'modern' => 'mix-manifest.json',
        ],
        'server' => [
            'manifestPath' => '@webroot/assets',
            'publicPath' => '/assets',
        ],
        'devServer' => [
            'manifestPath' => 'http://localhost:8080/',
            'publicPath' => 'http://localhost:8080/',
        ],
        'localFiles' => [
            'basePath' => '@webroot/assets',
            'criticalPrefix' => 'criticalcss/',
            'criticalSuffix' => '_critical.min.css',
        ],
    ],
];
```

Nothing special you need to alter in your `webpack.mix.js` file.

Then run the usual `npx mix` (if using the newer Laravel Mix).

**Comment by thisisjamessmith** [comment]
Even just the line `useDevServer: true` is giving me traumatic flashbacks. I understand now, more or less, what webpack's DevServer actually _is_, but I didn't at the time, and it was a major cause of my pain.

**Comment by engram-design** [comment]
Haha, I hear ya @thisisjamessmith I have so many better things to do than wrangle front-end build processes - just not my fav thing.

Anyway, would love a response sometime from the maintainers on what they'll do, if they're happy with a PR, etc.

**Comment by thisisjamessmith** [comment]
Well, I mean there already is a pull request here, and it seems to work fine: https://github.com/mister-bk/craft-plugin-mix/pull/20

**Comment by Konsti-O** [comment]
Please excuse the long wait. We will release more updates over the next few weeks and focus more on improving this plugin. We thank everyone for their loyalty so far :)
