### ISSUE TITLE
Craft 5 compatibility?

### ISSUE THREAD

**Issue by steve-moresoda** [mister-bk/craft-plugin-mix#23]
Hi, do you know when you will be ready for Craft 5? The Craft 5 upgrade utility has you down as not ready yet. 

<img width="459" alt="Screenshot 2024-03-27 at 10 47 52" src="https://github.com/mister-bk/craft-plugin-mix/assets/111141623/49a524c7-f5a2-4b43-8946-18a965503038">

**Comment by internetztube** [comment]
https://github.com/mister-bk/craft-plugin-mix/pull/24

**Comment by Konsti-O** [comment]
Thank you @internetztube . Your pull request was merged.
