### ISSUE TITLE
Asset Path being directly in @web

### ISSUE THREAD

**Issue by sergeifilippov** [mister-bk/craft-plugin-mix#6]
Hey, would it be possible to updated the module to allow you to set the `Asset Path` to be blank?

**Reason:** In projects, we put `js/css/img` folders directly in `web/{css,js,img}`.

**Comment by jackmu95** [comment]
@sergeifilippov You can just insert a `/` to get your wanted result.
The configurable paths get trimmed in the background automatically 👍

**Comment by jackmu95** [comment]
Closed by #7.
