### ISSUE TITLE
[FR] Hot Module Replacement support

### ISSUE THREAD

**Issue by benjamindavid** [mister-bk/craft-plugin-mix#8]
I was wondering if you had any plans to support Hot Module Replacement?
https://github.com/JeffreyWay/laravel-mix/blob/master/docs/hot-module-replacement.md

Thanks!

**Comment by jackmu95** [comment]
@benjamindavid HMR support would be awesome but I currently have no time to implement it.
A PR is always welcome :)

**Comment by benjamindavid** [comment]
@jackmu95 Thanks, will do!

**Comment by bryantAXS** [comment]
@benjamindavid it looks like you've got that HMR update in place, could we get that merged in here?
